### ISSUE TITLE
How to set Custom magin to every child layout?

### ISSUE THREAD

**Issue by Premjit-Developer** [AmrDeveloper/TreeView#1]
First of all congratulations to the dev for making this great easy to use TreeView library 👏.
**Describe the solution you'd like**
My feature request is about to get a set margin option in TreeNode by default for each child layout.  As you did in example projects extended custom class with TreeNode, i also tried the same to set my custom margin method but it didn't work for me.  So if you make a default margin option in TreeNode it will be easy for noob devs like me.

**Comment by AmrDeveloper** [comment]
Hello @Premjit-Chowdhury, 

Very happy that you loved it, I think it will be better to keep the default TreeNode object small and simple and anyone can extend it easily, if we add a default attribute that handles the margin, we should also add some other attributes, so I will try to extend the examples with margin and other examples

Thanks
Amr Hesham

**Comment by Premjit-Chowdhury** [comment]
Yeah, it would be very helpful.
