### ISSUE TITLE
Please add more relase so that we can implement treeview 

### ISSUE THREAD

**Issue by mdtuhinmia** [AmrDeveloper/TreeView#11]
Please add more release for Android treeview.Recently I added your library in my Android apps.But can't implement treeview.So add more release in GitHub

**Comment by AmrDeveloper** [comment]
Hello @mdtuhinmia, 

Can you please describe the problem because there are some release already and the problem mayn't be because releases, 

BTW i will release a small bug fix release today

Thanks
Amr Hesham
