### ISSUE TITLE
TreeNode isSelected

### ISSUE THREAD

**Issue by panliang-rm** [AmrDeveloper/TreeView#20]
![image](https://github.com/AmrDeveloper/TreeView/assets/54338815/43e69860-e874-4745-b665-34f8153d7906)
![image](https://github.com/AmrDeveloper/TreeView/assets/54338815/8fe4f24b-b87a-4c02-8f34-e075422b32fc)
when i use, only have log in select the catalog will be printed, the largest level  will not。 i can't selected the child treenode

**Comment by AmrDeveloper** [comment]
Hello @panliang-rm,

Thank you for reporting this issues, i have solved it today and will release it in next few hours `1.2.0`

**Comment by AmrDeveloper** [comment]
Please check the latest release

https://github.com/AmrDeveloper/TreeView/releases/tag/1.2.0

**Comment by panliang-rm** [comment]
Thanks your update, i want to know why need to update the sdk to 33, because i must update my project to 33

**Comment by panliang-rm** [comment]
i also notice when i collapse all child item, the state of selecet will be reset, how could i keep this state? Becase i  only use child item, just select the parent, it will collapse and selected, then child item will reset.

**Comment by AmrDeveloper** [comment]
> i also notice when i collapse all child item, the state of selecet will be reset, how could i keep this state? Becase i  only use child item, just select the parent, it will collapse and selected, then child item will reset.

Hello,

This is because the current implementation supports single selection only for example when you select any node it will unselect others,

What you want is multiple selection support, i am actually working on that
