### ISSUE TITLE
about style of item

### ISSUE THREAD

**Issue by panliang-rm** [AmrDeveloper/TreeView#23]
how could i change the default width of treeiew. The distance between the node and the node of the next layer is too large，so i want to change

**Comment by AmrDeveloper** [comment]
Hello @panliang-rm 

This can handled like any other views, you have your xml layout and recycler view so you can control padding and margin

Thank you

**Comment by panliang-rm** [comment]
sorry, i,don' t know why i can't get the current viewholder 
 TreeViewHolderFactory factory = (view, i) -> {
            addPlanTreeViewHolder = new AddPlanTreeViewHolder(view, context);
            return addPlanTreeViewHolder;
        };
is null

**Comment by panliang-rm** [comment]
And how could i get all treenodes, not just invisible

**Comment by panliang-rm** [comment]
When initializing, I set the `isExpanded` property for the node; the property is set successfully, but the display is incorrect—it does not expand.
