### ISSUE TITLE
Dont visualization

### ISSUE THREAD

**Issue by gohancrafting** [AmrDeveloper/TreeView#5]

**Comment by gohancrafting** [comment]
Hi, im trying to learn the use of the tree for personalize json. To iniciate in this world, the first thing im trying to do is a eassy tree, i follow all the steps but it didnt works. There is no error and nothing strange that i can see, but when i run the app, nothing appears in the screen. 
The main code:
![image](https://user-images.githubusercontent.com/116968573/198842523-c3fe22ce-f5eb-4f5b-9aea-c8db27bf4f57.png)
the view holder(the log never show up)
![image](https://user-images.githubusercontent.com/116968573/198842555-8b685e62-914e-40ab-81e9-8d9b2b21612a.png)
and the xml(the item, and the main) :
![image](https://user-images.githubusercontent.com/116968573/198842564-125cb20f-ac26-4841-9047-80f726c2cc5a.png)
![image](https://user-images.githubusercontent.com/116968573/198842577-1a916c04-01d7-4a86-a193-cd4a1afb2a0c.png)

**Comment by AmrDeveloper** [comment]
Hello @gohancrafting, 

For testing can you replace ConstraintLayout in item and the main with for example LinearLayout and try to set different background color for main, recycler, item so we can see which view has the problem, also try to add logs with same tag to check if view holder see them so we can identify the main problem and solve it

**Comment by epiphyllumbl** [comment]
Hello, I have the same problem，I have used LineLayout on the layout page，and The treeViewAdapter. getTreeNodes() and treeViewAdapter.getItemCount() method can return the correct value，but the recyclerView is black and nothing is displayed.

**Comment by finedayjun** [comment]
Hello @gohancrafting 

Try it with the code below

<androidx.recyclerview.widget.RecyclerView
            android:id="@+id/recycler_view"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            app:layoutManager="androidx.recyclerview.widget.LinearLayoutManager"/>

**Comment by exportdeveloper** [comment]
app:layoutManager="androidx.recyclerview.widget.LinearLayoutManager"
slove the problem 
thanks @finedayjun
