### ISSUE TITLE
Highlight selected item

### ISSUE THREAD

**Issue by fmeneuhe** [AmrDeveloper/TreeView#6]
Hi,
thanks a lot for this useful library.
Is possible to highlight a selected item? select a single choice item. 
Thanks

**Comment by AmrDeveloper** [comment]
Hello @fmeneuhe,

Thank you for your review, 

Yes it is possible, in TreeNode class there is an attribute that tells you if it is selected or not, also if it is expanded or not

https://github.com/AmrDeveloper/TreeView/blob/c8725943cd17d916ce3c5cbae93de8d8b572caa8/treeview/src/main/java/com/amrdeveloper/treeview/TreeNode.java#L40

So in the view holder, you can the background color if it selected and another color if it not selected you can choose any color and also change text colour, icons ...etc

Thanks
Amr Hesham
